# biome = "irr_hakur"
# biome = "aganandor"
# biome = "ezerast"
biome = "irr_umar"
# biome = "onomora"

[simulation]
lab_name = "RAY_VISION"
run_id = "97"

[populations]
## Irr'Hakur oasis pond
# sahlalga = 512
# mirajun = 256
# dunetide = 32
# gharlox = 16
# hakursa = 4

## Aganandor mountain lake
# lodril = 512
# vanyr = 32
# thalvyrn = 8
# myrrkul = 2

## Ezerast salt marsh
# qyrsel = 288
# ozyrae = 144
# veytris = 72
# brisqal = 24
# chalyth = 6
# vorqualis = 2

## Irr'Umar swamp
vyrmosa = 768
qirval = 48
lorynth = 24
dravym = 12
zyralith = 6

## Onomora thermal spring basin
# lyrvane = 128
# omyra = 32
# cindralys = 16
# pyrralis = 8
# onytheron = 2
