# biome = "irr_hakur"
# biome = "aganandor"
biome = "ezerast"
# biome = "irr_umar"
# biome = "onomora"

[simulation]
lab_name = "RAY_VISION"
run_id = "84"

[populations]
## Irr'Hakur oasis pond
# sahlalga = 512
# mirajun = 256
# dunetide = 32
# gharlox = 16
# hakursa = 4

## Aganandor mountain lake
# lodril = 512
# vanyr = 32
# thalvyrn = 8
# myrrkul = 2

## Ezerast salt marsh
qyrsel = 72
ozyrae = 36
veytris = 18
brisqal = 12
chalyth = 6
vorqualis = 1

## Irr'Umar swamp
# vyrmosa = 748
# qirval = 27
# lorynth = 27
# dravym = 11
# zyralith = 2

## Onomora thermal spring basin
# lyrvane = 128
# omyra = 32
# cindralys = 16
# pyrralis = 8
# onytheron = 2
